In [297]:
'''select first 50 profiles'''

import pandas
import numpy as np
df = pandas.read_excel('texas_phone_profiles.xlsx')

'''get only the phone number'''
phone_df=df['phone']
               


''' extracting the information in each cell and put it in a phone_lst'''
# phones_lst= []
# for p in df["phone"]:
#     phones_lst.append(p)
# #print len(phones_lst)
'''set the number of document that we want'''
numcel =50 
'''extract the phone column of numcel number'''
#mydf = df[numcel:2*numcel]["phone"]
mydf = df[:numcel]["phone"]
print "shape", mydf.shape
#print mydf
'''create a list of all cells values'''
my_phone_list=mydf.tolist()
#a = mydf[0].encode('ascii')
#print len(my_phone_list) 


all_phones = {}
for i in range(numcel):
#for i in np.arange(20, 40, 1):
    #print i
    mycurr_list = my_phone_list[i]
    
    a = mycurr_list
    
    
#'''clean the string '''
    a=a.replace('[','')
    a=a.replace(']','')
    a=a.replace('(','')
    a=a.replace(') ','-')
    a=a.replace(' ', '')
    
    #print "Cleaned List String"
    #print a
    
    a_splitted = a.split(",")
    
    #print "Split List"
    #print a_splitted
    
    set_a_splitted = list(set(a_splitted))
    
    #print "set",set_a_splitted#np.unique(a_splitted)
    #print "length of a:",len(set_a_splitted)

    for j in range(len(set_a_splitted)):
        myPhone = set_a_splitted[j]#str(a_splitted[j])
#         myPhone = myPhone.replace('[','')
#         myPhone = myPhone.replace(']','')
#         myPhone = myPhone.replace('(','')
#         myPhone = myPhone.replace(') ','-')
#         #print j
#         #print((myPhone))
    
        if myPhone in all_phones.keys():
            all_phones[myPhone] = all_phones[myPhone] + 1
        else:
            all_phones[myPhone] = 1
            
            
            
print(all_phones)
'''frequency formula'''
'number of documents which target occurs/total number of crawled data'
all_phones_df = pandas.DataFrame(all_phones.items(), columns=['phone_pred', 'count'])
all_phones_df =all_phones_df[all_phones_df["phone_pred"]!=""]
print all_phones_df.shape[0]
#print all_phones_df
all_phones_df['freq'] = 100*all_phones_df['count']/all_phones_df.shape[0]
print(all_phones_df)

shape (50,)
{u'': 1, u"'520-858-4270'": 1, u"'214-424-9818'": 1, u"'214-778-7186'": 15, u"'512-662-8346'": 1, u"'806-391-7046'": 1, u"'903-336-7983'": 1, u"'214-727-1012'": 1, u"'346-234-0987'": 1, u"'281-793-2053'": 1, u"'713-261-5570'": 1, u"'575-343-0022'": 1, u"'713-705-3494'": 5, u"'512-651-2204'": 1, u"'469-289-1398'": 1, u"'702-504-6021'": 1, u"'972-480-1059'": 1, u"'972-246-8263'": 1, u"'817-723-4669'": 1, u"'414-510-9294'": 1, u"'915-630-0356'": 1, u"'503-961-0629'": 1, u"'214-659-3200'": 1, u"'210-518-6404'": 1, u"'424-285-3535'": 1, u"'312-508-3270'": 1, u"'832-638-0298'": 1, u"'682-205-9569'": 1, u"'214-694-6256'": 1, u"'702-769-8167'": 1, u"'832-503-5702'": 1, u"'214-809-0704'": 1, u"'214-715-3313'": 1, u"'214-710-5917'": 1, u"'504-615-4265'": 1, u"'623-500-7982'": 1, u"'979-475-4157'": 1, u"'832-782-0259'": 1, u"'210-739-3842'": 1, u"'210-833-5770'": 1, u"'415-305-1975'": 1, u"'803-626-5948'": 1, u"'469-394-4575'": 2, u"'414-574-6077'": 1, u"'214-721-4078'": 1, u"'818-732-5418'": 1, u"'818-233-3220'": 1, u"'281-839-5492'": 1, u"'214-299-1818'": 2}
48
        phone_pred  count       freq
1   '520-858-4270'      1   2.083333
2   '214-424-9818'      1   2.083333
3   '214-778-7186'     15  31.250000
4   '512-662-8346'      1   2.083333
5   '806-391-7046'      1   2.083333
6   '903-336-7983'      1   2.083333
7   '214-727-1012'      1   2.083333
8   '346-234-0987'      1   2.083333
9   '281-793-2053'      1   2.083333
10  '713-261-5570'      1   2.083333
11  '575-343-0022'      1   2.083333
12  '713-705-3494'      5  10.416667
13  '512-651-2204'      1   2.083333
14  '469-289-1398'      1   2.083333
15  '702-504-6021'      1   2.083333
16  '972-480-1059'      1   2.083333
17  '972-246-8263'      1   2.083333
18  '817-723-4669'      1   2.083333
19  '414-510-9294'      1   2.083333
20  '915-630-0356'      1   2.083333
21  '503-961-0629'      1   2.083333
22  '214-659-3200'      1   2.083333
23  '210-518-6404'      1   2.083333
24  '424-285-3535'      1   2.083333
25  '312-508-3270'      1   2.083333
26  '832-638-0298'      1   2.083333
27  '682-205-9569'      1   2.083333
28  '214-694-6256'      1   2.083333
29  '702-769-8167'      1   2.083333
30  '832-503-5702'      1   2.083333
31  '214-809-0704'      1   2.083333
32  '214-715-3313'      1   2.083333
33  '214-710-5917'      1   2.083333
34  '504-615-4265'      1   2.083333
35  '623-500-7982'      1   2.083333
36  '979-475-4157'      1   2.083333
37  '832-782-0259'      1   2.083333
38  '210-739-3842'      1   2.083333
39  '210-833-5770'      1   2.083333
40  '415-305-1975'      1   2.083333
41  '803-626-5948'      1   2.083333
42  '469-394-4575'      2   4.166667
43  '414-574-6077'      1   2.083333
44  '214-721-4078'      1   2.083333
45  '818-732-5418'      1   2.083333
46  '818-233-3220'      1   2.083333
47  '281-839-5492'      1   2.083333
48  '214-299-1818'      2   4.166667

In [298]:
'''labeled data to excel file'''
import pandas as pd
# Import the excel file and call it xls_file
xls_label_file = pd.ExcelFile('./Labeling_Spreadsheet_Texas_Profiles_Nov_2017.xlsx')
df_labeled = xls_label_file.parse('sheet1')
phone_labeled = df_labeled[:numcel]["phone_number [XXX-XXX-XXXX], 000 if no area code"]
#phone_labeled = df_labeled[numcel:2*numcel]["phone_number [XXX-XXX-XXXX], 000 if no area code"]
labeled_phone =[]
for i in phone_labeled:
    labeled_phone.append(i)
labeled_phone

[u'832-638-0298',
 u'818-732-5418',
 u'281-839-5492',
 u'210-739-3842',
 u'806-391-7046',
 u'210-518-6404',
 u'214-424-9818',
 u'214-710-5917',
 u'214-299-1818',
 u'832-503-5702',
 u'214-727-1012',
 u'504-615-4265',
 u'210-833-5770',
 u'414-574-6077',
 u'312-508-3270',
 u'none',
 u'none',
 u'713-261-5570',
 u'214-659-3200',
 u'214-715-3313',
 u'520-858-4270',
 u'623-500-7982',
 u'281-793-2053',
 u'972-480-1059',
 u'682-205-9569',
 u'512-662-8346',
 u'424-285-3535',
 u'214-299-1818',
 u'214-809-0704',
 u'903-336-7983',
 u'469-289-1398',
 u'818-233-3220',
 u'214-694-6256',
 u'none',
 u'702-769-8167',
 u'512-651-2204',
 u'915-630-0356',
 u'469-394-4575',
 u'832-2782-632',
 u'979-475-4157',
 u'323-830-5260',
 u'469-394-4575',
 u'803-626-5948',
 u'972-246-8263',
 u'214-721-4078',
 u'415-305-1975',
 u'575-343-0022',
 u'832-782-0259',
 u'214-778-7186',
 u'817-723-4669']

In [299]:
phoneset = set(labeled_phone)
all_phones_df["label"] = 0

phoneset = (labeled_phone)
pp = []
for y in all_phones_df["phone_pred"]:
    pp.append(y.replace(" '","").replace("'",""))

all_phones_df["phone_pred"] = pp
all_phones_df["label"]= all_phones_df["phone_pred"].apply(lambda x: 1 if x in (phoneset) else 0)
print(all_phones_df)
# writer = pd.ExcelWriter('first_part_phone.xlsx')
# all_phones_df.to_excel(writer,'Sheet1')
# writer.save()

      phone_pred  count       freq  label
1   520-858-4270      1   2.083333      1
2   214-424-9818      1   2.083333      1
3   214-778-7186     15  31.250000      1
4   512-662-8346      1   2.083333      1
5   806-391-7046      1   2.083333      1
6   903-336-7983      1   2.083333      1
7   214-727-1012      1   2.083333      1
8   346-234-0987      1   2.083333      0
9   281-793-2053      1   2.083333      1
10  713-261-5570      1   2.083333      1
11  575-343-0022      1   2.083333      1
12  713-705-3494      5  10.416667      0
13  512-651-2204      1   2.083333      1
14  469-289-1398      1   2.083333      1
15  702-504-6021      1   2.083333      0
16  972-480-1059      1   2.083333      1
17  972-246-8263      1   2.083333      1
18  817-723-4669      1   2.083333      1
19  414-510-9294      1   2.083333      0
20  915-630-0356      1   2.083333      1
21  503-961-0629      1   2.083333      0
22  214-659-3200      1   2.083333      1
23  210-518-6404      1   2.083333      1
24  424-285-3535      1   2.083333      1
25  312-508-3270      1   2.083333      1
26  832-638-0298      1   2.083333      1
27  682-205-9569      1   2.083333      1
28  214-694-6256      1   2.083333      1
29  702-769-8167      1   2.083333      1
30  832-503-5702      1   2.083333      1
31  214-809-0704      1   2.083333      1
32  214-715-3313      1   2.083333      1
33  214-710-5917      1   2.083333      1
34  504-615-4265      1   2.083333      1
35  623-500-7982      1   2.083333      1
36  979-475-4157      1   2.083333      1
37  832-782-0259      1   2.083333      1
38  210-739-3842      1   2.083333      1
39  210-833-5770      1   2.083333      1
40  415-305-1975      1   2.083333      1
41  803-626-5948      1   2.083333      1
42  469-394-4575      2   4.166667      1
43  414-574-6077      1   2.083333      1
44  214-721-4078      1   2.083333      1
45  818-732-5418      1   2.083333      1
46  818-233-3220      1   2.083333      1
47  281-839-5492      1   2.083333      1
48  214-299-1818      2   4.166667      1

In [300]:
'''investigate for the thresholds'''
from sklearn.metrics import precision_recall_curve
precision, recall, thresholds = precision_recall_curve(all_phones_df["label"],all_phones_df["freq"])
print "precision:", precision
print "recall:", recall
print "thresholds:", thresholds

precision: [ 0.89583333  0.75        0.5         1.          1.        ]
recall: [ 1.          0.06976744  0.02325581  0.02325581  0.        ]
thresholds: [  2.08333333   4.16666667  10.41666667  31.25      ]

In [305]:
'''test thresholshold = 2 on second 50 document'''

'''select first 50 profiles'''

import pandas
import numpy as np
df = pandas.read_excel('texas_phone_profiles.xlsx')

'''get only the phone number'''
phone_df=df['phone']

                    


''' extracting the information in each cell and put it in a phone_lst'''
# phones_lst= []
# for p in df["phone"]:
#     phones_lst.append(p)
# #print len(phones_lst)
'''set the number of document that we want'''
numcel =50 
'''extract the phone column of numcel number'''
my_test_df = df[numcel:2*numcel]["phone"]
#mydf = df[:numcel]["phone"]
print "shape", my_test_df.shape
#print mydf
'''create a list of all cells values'''
my_phone_list=my_test_df.tolist()


all_test_phones = {}
for i in range(numcel):

    mycurr_list = my_phone_list[i]
    
    a = mycurr_list
    
    
#'''clean the string '''
    a=a.replace('[','')
    a=a.replace(']','')
    a=a.replace('(','')
    a=a.replace(') ','-')
    a=a.replace(' ', '')
    
    
    a_splitted = a.split(",")
    
    set_a_splitted = list(set(a_splitted))
    

    for j in range(len(set_a_splitted)):
        myPhone = set_a_splitted[j]#str(a_splitted[j])

        if myPhone in all_test_phones.keys():
            all_test_phones[myPhone] = all_test_phones[myPhone] + 1
        else:
            all_test_phones[myPhone] = 1
            
            
            
#print(all_test_phones.items())
'''frequency formula'''
'number of documents which target occurs/total number of crawled data'
all_test_phones_df = pandas.DataFrame(all_test_phones.items(), columns=['phone_pred', 'count'])
#print all_phones_df.shape
all_test_phones_df =all_test_phones_df[all_test_phones_df["phone_pred"]!=""]
all_test_phones_df['freq'] = 100*(all_test_phones_df['count']/all_test_phones_df.shape[0])#numcel)
#print(all_test_phones_df)

all_test_phones_df['label_pred_corrected']= all_test_phones_df['freq'].apply(lambda x: 0 if x>2.08333333 else 1)
all_test_phones_df

shape (50,)

        phone_pred  count       freq  label_pred_corrected
0   '806-300-4029'      1   1.960784                     1
1   '720-722-2533'      1   1.960784                     1
2   '209-627-0816'      1   1.960784                     1
3   '713-806-2316'      1   1.960784                     1
4   '210-982-5934'      1   1.960784                     1
5   '214-809-5362'      1   1.960784                     1
6   '214-778-7186'      7  13.725490                     0
7   '312-854-4571'      1   1.960784                     1
8   '512-553-8366'      1   1.960784                     1
9   '817-217-3485'      1   1.960784                     1
10  '214-643-5334'      1   1.960784                     1
11  '469-364-0059'      1   1.960784                     1
12  '646-374-4646'      1   1.960784                     1
13  '512-748-7083'      1   1.960784                     1
14  '214-674-9445'      1   1.960784                     1
15  '512-300-7300'      1   1.960784                     1
16  '281-793-2053'      1   1.960784                     1
17  '469-447-5530'      1   1.960784                     1
18  '713-325-4563'      1   1.960784                     1
19  '806-474-9635'      1   1.960784                     1
20  '214-853-3906'      1   1.960784                     1
21  '512-383-9090'      2   3.921569                     0
22  '512-553-8478'      1   1.960784                     1
23  '817-349-1507'      1   1.960784                     1
24  '281-381-1412'      1   1.960784                     1
25  '214-335-2528'      1   1.960784                     1
26  '323-620-9814'      1   1.960784                     1
27  '210-987-7197'      1   1.960784                     1
28  '423-903-2927'      1   1.960784                     1
29  '857-496-5987'      1   1.960784                     1
30  '972-803-7666'      1   1.960784                     1
31  '972-391-7708'      1   1.960784                     1
32  '682-232-4680'      1   1.960784                     1
33  '254-577-1128'      1   1.960784                     1
34  '214-694-6256'      1   1.960784                     1
35  '817-443-1202'      1   1.960784                     1
36  '347-909-4205'      1   1.960784                     1
37  '281-846-4972'      1   1.960784                     1
38  '214-586-9012'      1   1.960784                     1
39  '347-965-0112'      1   1.960784                     1
40  '713-705-3494'      7  13.725490                     0
41  '682-325-1691'      2   3.921569                     0
42  '817-298-9815'      1   1.960784                     1
43  '361-704-0015'      1   1.960784                     1
44  '915-881-3181'      1   1.960784                     1
45  '214-916-1341'      1   1.960784                     1
46  '469-713-6169'      1   1.960784                     1
47  '619-251-5411'      1   1.960784                     1
48  '469-844-7358'      1   1.960784                     1
49  '214-299-1818'      1   1.960784                     1
50  '210-420-8591'      1   1.960784                     1

In [333]:
'''use labeled data to excel file for test set'''
import pandas as pd

phone_labeled_test = df_labeled[numcel:2*numcel]["phone_number [XXX-XXX-XXXX], 000 if no area code"]
labeled_phone_test =[]
'''create a list of all phones in handlabeled file.'''
for i in phone_labeled_test: 
    i = i.replace(" ","") '''taking care of morethan one phone in a cell'''
    
    if i.find(',')!=-1:
       
        lst_1 = i.split(',')
        
        for p in lst_2:
            labeled_phone_test.append(p)  
    else:
        labeled_phone_test.append(i)
labeled_phone_test

[u'281-793-2053',
 u'214-694-6256',
 u'456-713-6169',
 u'817-298-9815',
 u'214-299-1818',
 u'281-381-1412',
 u'817-349-1507',
 u'214-809-5362',
 u'720-722-2533',
 u'512-553-8366',
 u'209-627-0816',
 u'512-553-8478',
 u'682-232-4680',
 u'214-853-3906',
 u'469-447-5530',
 u'646-374-4646',
 u'214-916-1341',
 u'361-704-0015',
 u'806-300-4029',
 u'806-474-9635',
 u'972-803-7666',
 u'682-549-9745',
 u'469-844-7358',
 u'619-251-5411',
 u'323-620-9814',
 u'512-300-7300',
 u'214-643-5334',
 u'214-674-9445',
 u'857-496-5987',
 u'210-982-5934',
 u'210-420-8591',
 u'682-549-9745',
 u'512-383-9090',
 u'817-217-3485',
 u'713-806-2316',
 u'469-364-0059',
 u'512-748-7083',
 u'512-783-1291',
 u'214-586-9012',
 u'347-965-0112',
 u'347-909-4205',
 u'312-854-4571',
 u'817-443-1202',
 u'210-987-7197',
 u'972-391-7708',
 u'713-325-4563',
 u'214-335-2528',
 u'254-577-1128',
 u'512-383-9090',
 u'281-846-4972',
 u'423-903-2927']

In [334]:
'''Label column has value of 1 if the phone number belongs to the hand label set, otherwise, 0 '''
phoneset = set(labeled_phone_test)
all_test_phones_df["label"] = 0
phoneset = (labeled_phone_test)
pp = []
for y in all_test_phones_df["phone_pred"]:
    pp.append(y.replace(" '","").replace("'",""))

all_test_phones_df["phone_pred"] = pp
all_test_phones_df["label"]= all_test_phones_df["phone_pred"].apply(lambda x: 1 if x in (phoneset) else 0)
print(all_test_phones_df)

      phone_pred  count       freq  label_pred_corrected  label
0   806-300-4029      1   1.960784                     1      1
1   720-722-2533      1   1.960784                     1      1
2   209-627-0816      1   1.960784                     1      1
3   713-806-2316      1   1.960784                     1      1
4   210-982-5934      1   1.960784                     1      1
5   214-809-5362      1   1.960784                     1      1
6   214-778-7186      7  13.725490                     0      0
7   312-854-4571      1   1.960784                     1      1
8   512-553-8366      1   1.960784                     1      1
9   817-217-3485      1   1.960784                     1      1
10  214-643-5334      1   1.960784                     1      1
11  469-364-0059      1   1.960784                     1      1
12  646-374-4646      1   1.960784                     1      1
13  512-748-7083      1   1.960784                     1      1
14  214-674-9445      1   1.960784                     1      1
15  512-300-7300      1   1.960784                     1      1
16  281-793-2053      1   1.960784                     1      1
17  469-447-5530      1   1.960784                     1      1
18  713-325-4563      1   1.960784                     1      1
19  806-474-9635      1   1.960784                     1      1
20  214-853-3906      1   1.960784                     1      1
21  512-383-9090      2   3.921569                     0      1
22  512-553-8478      1   1.960784                     1      1
23  817-349-1507      1   1.960784                     1      1
24  281-381-1412      1   1.960784                     1      1
25  214-335-2528      1   1.960784                     1      1
26  323-620-9814      1   1.960784                     1      1
27  210-987-7197      1   1.960784                     1      1
28  423-903-2927      1   1.960784                     1      1
29  857-496-5987      1   1.960784                     1      1
30  972-803-7666      1   1.960784                     1      1
31  972-391-7708      1   1.960784                     1      1
32  682-232-4680      1   1.960784                     1      1
33  254-577-1128      1   1.960784                     1      1
34  214-694-6256      1   1.960784                     1      1
35  817-443-1202      1   1.960784                     1      1
36  347-909-4205      1   1.960784                     1      1
37  281-846-4972      1   1.960784                     1      1
38  214-586-9012      1   1.960784                     1      1
39  347-965-0112      1   1.960784                     1      1
40  713-705-3494      7  13.725490                     0      0
41  682-325-1691      2   3.921569                     0      0
42  817-298-9815      1   1.960784                     1      1
43  361-704-0015      1   1.960784                     1      1
44  915-881-3181      1   1.960784                     1      0
45  214-916-1341      1   1.960784                     1      1
46  469-713-6169      1   1.960784                     1      0
47  619-251-5411      1   1.960784                     1      1
48  469-844-7358      1   1.960784                     1      1
49  214-299-1818      1   1.960784                     1      1
50  210-420-8591      1   1.960784                     1      1

In [335]:
'''calculate the precision and recall'''

from sklearn.metrics import recall_score,precision_score
y_true = all_test_phones_df["label"]
y_pred = all_test_phones_df['label_pred_corrected']
recall_corrected = recall_score(y_true, y_pred, average='binary') 
print "recall:",recall_corrected
precision_corrected = precision_score(y_true, y_pred, average='binary') 
print "precision:",precision_corrected

recall: 0.978260869565
precision: 0.957446808511